[tool.poetry]
name = "starlette-graphql"
version = "0.0.1"
description = "Starlette graphql extension."
authors = ["syfun <sunyu418@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
python-gql = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
